ALTER TYPE "ListingStatus" ADD VALUE IF NOT EXISTS 'DRAFT';
ALTER TYPE "ListingStatus" ADD VALUE IF NOT EXISTS 'UNDER_REVIEW';
ALTER TYPE "ListingStatus" ADD VALUE IF NOT EXISTS 'ACTIVE';
ALTER TYPE "ListingStatus" ADD VALUE IF NOT EXISTS 'INACTIVE';

