"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import StatusBadge from "@/components/StatusBadge";

const filters = [["ALL", "All"], ["DRAFT", "Draft"], ["PENDING", "Pending"], ["UNDER_REVIEW", "Under Review"], ["APPROVED", "Approved"], ["ACTIVE", "Active"], ["REJECTED", "Rejected"], ["INACTIVE", "Inactive"]];
export default function PropertiesPage() {
  const [data, setData] = useState(null); const [status, setStatus] = useState("ALL"); const [query, setQuery] = useState(""); const [error, setError] = useState("");
  useEffect(() => { const params = new URLSearchParams({ status, q: query }); fetch(`/api/admin/properties?${params}`).then(async (response) => { const result = await response.json(); if (!response.ok) throw new Error(result.error); setData(result); }).catch((reason) => setError(reason.message)); }, [status, query]);
  if (error) return <p className="rounded-xl bg-red-50 p-4 text-red-700">{error}</p>;
  if (!data) return <p className="text-sm text-slate-500">Loading properties...</p>;
  return <div><div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="font-display text-3xl text-amber-950">Properties</h2><p className="mt-1 text-sm text-slate-500">Review and manage every listing.</p></div><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search property, owner, city..." className="rounded-xl border border-amber-200 bg-white px-4 py-3 text-sm" /></div><div className="mt-6 flex gap-2 overflow-x-auto pb-2">{filters.map(([value, label]) => <button key={value} onClick={() => setStatus(value)} className={`whitespace-nowrap rounded-full px-4 py-2 text-xs font-bold ${status === value ? "bg-amber-800 text-white" : "bg-white text-slate-600"}`}>{label} {value !== "ALL" && `(${data.counts[value] || 0})`}</button>)}</div><div className="mt-4 overflow-x-auto rounded-2xl border border-amber-100 bg-white"><table className="w-full min-w-[800px] text-left text-sm"><thead className="bg-amber-50 text-xs uppercase text-slate-500"><tr><th className="p-4">Property</th><th className="p-4">Owner</th><th className="p-4">Location</th><th className="p-4">Price</th><th className="p-4">Status</th><th className="p-4">Action</th></tr></thead><tbody>{data.listings.map((listing) => <tr key={listing.id} className="border-t border-slate-100"><td className="p-4"><div className="flex items-center gap-3">{listing.photos[0] && <img src={listing.photos[0].url} alt="" className="h-12 w-16 rounded-lg object-cover" />}<span className="font-semibold">{listing.title}</span></div></td><td className="p-4">{listing.owner.name}<br /><span className="text-xs text-slate-500">{listing.owner.email}</span></td><td className="p-4">{listing.area}, {listing.city}</td><td className="p-4">₹{Number(listing.price).toLocaleString("en-IN")}</td><td className="p-4"><StatusBadge status={listing.status} /></td><td className="p-4"><Link href={`/admin/properties/${listing.id}`} className="font-semibold text-amber-800 hover:underline">Review</Link></td></tr>)}</tbody></table>{!data.listings.length && <p className="p-10 text-center text-sm text-slate-500">No properties found.</p>}</div></div>;
}
