"use client";

import { useEffect, useState } from "react";
import { useRouter, useParams } from "next/navigation";
import Link from "next/link";
import StatusBadge from "@/components/StatusBadge";

const statuses = ["DRAFT", "PENDING", "UNDER_REVIEW", "APPROVED", "ACTIVE", "REJECTED", "INACTIVE"];
export default function PropertyReviewPage() {
  const { id } = useParams(); const router = useRouter(); const [listing, setListing] = useState(null); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { fetch(`/api/admin/properties/${id}`).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.error); setListing(data.listing); }).catch((reason) => setError(reason.message)); }, [id]);
  async function changeStatus(status) { const reason = status === "REJECTED" ? prompt("Reason for rejection:") : undefined; if (status === "REJECTED" && reason === null) return; setSaving(true); const response = await fetch(`/api/admin/properties/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status, reason }) }); const data = await response.json(); setSaving(false); if (!response.ok) return setError(data.error); setListing((current) => ({ ...current, ...data.listing })); }
  if (error) return <p className="rounded-xl bg-red-50 p-4 text-red-700">{error}</p>;
  if (!listing) return <p className="text-sm text-slate-500">Loading property...</p>;
  return <div><Link href="/admin/properties" className="text-sm font-semibold text-gray-800">← Back to properties</Link><div className="mt-4 flex flex-wrap items-center justify-between gap-4"><div><h2 className="font-display text-3xl text-gray-950">{listing.title}</h2><p className="mt-1 text-sm text-slate-500">{listing.area}, {listing.city}</p></div><StatusBadge status={listing.status} /></div><div className="mt-6 grid gap-6 lg:grid-cols-[1fr_320px]"><section className="space-y-6"><div className="grid gap-3 sm:grid-cols-2">{listing.photos.map((photo) => <img key={photo.id} src={photo.url} alt={listing.title} className="aspect-video w-full rounded-xl object-cover" />)}</div><Panel title="Property details"><dl className="grid gap-3 sm:grid-cols-2">{[["Type", listing.propertyType], ["Purpose", listing.purpose], ["Price", `₹${Number(listing.price).toLocaleString("en-IN")}`], ["Area", `${listing.sizeValue || "-"} ${listing.sizeUnit || ""}`], ["Bedrooms", listing.bedrooms || "-"], ["Bathrooms", listing.bathrooms || "-"]].map(([label, value]) => <div key={label}><dt className="text-xs text-slate-500">{label}</dt><dd className="font-semibold">{value}</dd></div>)}</dl>{listing.description && <p className="mt-5 text-sm leading-6 text-slate-600">{listing.description}</p>}</Panel><Panel title="Owner details"><p className="font-semibold">{listing.owner.name}</p><p className="text-sm text-slate-500">{listing.owner.email}<br />{listing.owner.phone}</p><p className="mt-2 text-xs text-slate-500">Account: {listing.owner.verificationStatus}</p></Panel></section><aside className="h-fit rounded-2xl border border-gray-100 bg-white p-5"><h3 className="font-display text-2xl">Status management</h3><select value={listing.status} disabled={saving} onChange={(event) => changeStatus(event.target.value)} className="mt-4 w-full rounded-xl border border-slate-200 px-3 py-3 text-sm">{statuses.map((status) => <option key={status}>{status}</option>)}</select><p className="mt-3 text-xs text-slate-500">Changes are saved immediately and logged in admin activity.</p>{listing.rejectionReason && <p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">Reason: {listing.rejectionReason}</p>}</aside></div></div>;
}
function Panel({ title, children }) { return <section className="rounded-2xl border border-gray-100 bg-white p-5"><h3 className="mb-4 font-display text-2xl">{title}</h3>{children}</section>; }
