"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import StatusBadge from "@/components/StatusBadge";

const cards = [["totalUsers", "Total Users"], ["activeUsers", "Active Users"], ["totalListings", "Total Properties"], ["pendingListings", "Pending Properties"], ["approvedListings", "Approved Properties"], ["rejectedListings", "Rejected Properties"], ["totalDocuments", "Total Documents"], ["pendingDocuments", "Pending Documents"], ["verifiedDocuments", "Verified Documents"], ["rejectedDocuments", "Rejected Documents"]];

export default function AdminDashboard() {
  const [data, setData] = useState(null);
  const [error, setError] = useState("");
  useEffect(() => { fetch("/api/admin/dashboard").then(async (response) => { const result = await response.json(); if (!response.ok) throw new Error(result.error); setData(result); }).catch((reason) => setError(reason.message)); }, []);
  if (error) return <p className="rounded-xl bg-red-50 p-4 text-red-700">{error}</p>;
  if (!data) return <p className="text-sm text-slate-500">Loading dashboard...</p>;
  return <div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([key, label]) => <div key={key} className="rounded-2xl border border-amber-100 bg-white p-5 shadow-sm"><p className="text-xs font-semibold text-slate-500">{label}</p><p className="mt-2 font-display text-3xl text-amber-950">{data.stats[key].toLocaleString("en-IN")}</p></div>)}</div><div className="mt-8 grid gap-8 xl:grid-cols-2"><section className="rounded-2xl border border-amber-100 bg-white p-5"><h2 className="font-display text-2xl">Quick actions</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{[["/admin/users/pending", "Review Pending Users"], ["/admin/documents", "Verify Documents"], ["/admin/properties?status=PENDING", "Review Pending Properties"], ["/admin/properties?status=ACTIVE", "View Active Properties"]].map(([href, label]) => <Link key={href} href={href} className="rounded-xl bg-amber-50 px-4 py-3 text-sm font-semibold text-amber-900 hover:bg-amber-100">{label}</Link>)}</div></section><section className="rounded-2xl border border-amber-100 bg-white p-5"><h2 className="font-display text-2xl">Recent activity</h2><div className="mt-4 divide-y divide-slate-100">{data.audits.map((audit) => <p key={audit.id} className="py-3 text-sm"><strong>{audit.admin.name}</strong> {audit.action.replaceAll("_", " ")}<span className="ml-2 text-xs text-slate-500">{new Date(audit.createdAt).toLocaleString("en-IN")}</span></p>)}{!data.audits.length && <p className="py-3 text-sm text-slate-500">No admin activity yet.</p>}</div></section></div><section className="mt-8 rounded-2xl border border-amber-100 bg-white p-5"><h2 className="font-display text-2xl">Recent users</h2><div className="mt-4 divide-y divide-slate-100">{data.recentUsers.map((user) => <div key={user.id} className="flex items-center justify-between gap-4 py-3"><span><strong>{user.name}</strong><span className="ml-2 text-sm text-slate-500">{user.email} · {new Date(user.createdAt).toLocaleDateString("en-IN")}</span></span><span className="rounded-full bg-amber-50 px-3 py-1 text-xs font-bold">{user.verificationStatus}</span></div>)}</div></section><section className="mt-8 rounded-2xl border border-amber-100 bg-white p-5"><h2 className="font-display text-2xl">Recent properties</h2><div className="mt-4 divide-y divide-slate-100">{data.recentListings.map((listing) => <Link href={`/admin/properties/${listing.id}`} key={listing.id} className="flex items-center justify-between gap-4 py-3"><span><strong>{listing.title}</strong><span className="ml-2 text-sm text-slate-500">{listing.city} · {listing.owner.name}</span></span><StatusBadge status={listing.status} /></Link>)}</div></section></div>;
}
