"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Building2, FileText, Heart, Home, LogOut, MapPin, Menu, Pencil, UserRound, X } from "lucide-react";
import { formatPrice } from "@/lib/formatters";
import UserDocuments from "@/components/UserDocuments";

const roleLabel = { BUYER: "Buyer", OWNER: "Property Owner", BROKER: "Property Broker" };
const nav = [["overview", "Overview", Home], ["profile", "My Profile", UserRound], ["saved", "Saved Properties", Heart], ["documents", "My Documents", FileText], ["posted", "My Posted Properties", Building2], ["preferences", "Buyer / Renter Details", MapPin]];
const blank = { name: "", phone: "", preferredCity: "", preferredLocation: "", preferredPropertyType: "", budgetRange: "", preferredBhk: "", searchPurpose: "" };
const date = (value) => value ? new Date(value).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" }) : "—";

export default function UserProfileDashboard() {
  const router = useRouter();
  const [section, setSection] = useState("overview");
  const [menu, setMenu] = useState(false);
  const [profile, setProfile] = useState(null);
  const [counts, setCounts] = useState({ saved: 0, posted: 0, documents: 0 });
  const [saved, setSaved] = useState([]); const [docs, setDocs] = useState([]); const [posted, setPosted] = useState([]);
  const [editing, setEditing] = useState(false); const [form, setForm] = useState(blank); const [notice, setNotice] = useState(""); const [error, setError] = useState("");
  const load = async () => {
    const options = { credentials: "include", cache: "no-store" };
    const [p, s, d, l] = await Promise.all([fetch("/api/profile", options), fetch("/api/profile/saved-properties", options), fetch("/api/profile/documents", options), fetch("/api/profile/posted-properties", options)]);
    if (p.status === 401) return router.replace("/login?next=/dashboard");
    const profileData = await p.json(); setProfile(profileData.user); setCounts(profileData.counts || {}); setForm({ ...blank, ...profileData.user });
    setSaved((await s.json().catch(() => ({}))).listings || []); setDocs((await d.json().catch(() => ({}))).documents || []); setPosted((await l.json().catch(() => ({}))).listings || []);
  };
  // The dashboard has a one-time authenticated data load on mount.
  // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps
  useEffect(() => { load().catch(() => setError("We could not load your dashboard. Please refresh and try again.")); }, []);
  const selectSection = (key) => { setSection(key); setMenu(false); setNotice(""); };
  const saveProfile = async (event) => { event.preventDefault(); setError(""); const r = await fetch("/api/profile", { method: "PUT", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const data = await r.json(); if (!r.ok) return setError(data.error || "Could not save your profile"); setProfile(data.user); setForm({ ...blank, ...data.user }); setEditing(false); setNotice("Profile updated successfully."); };
  const removeSaved = async (id) => { const r = await fetch(`/api/profile/saved-properties?listingId=${encodeURIComponent(id)}`, { method: "DELETE", credentials: "include" }); if (r.ok) { setSaved((items) => items.filter((item) => item.id !== id)); setCounts((value) => ({ ...value, saved: Math.max(0, value.saved - 1) })); setNotice("Property removed from saved properties."); } };
  const deleteListing = async (id) => { if (!window.confirm("Delete this property listing?")) return; const r = await fetch(`/api/listings/${id}`, { method: "DELETE", credentials: "include" }); if (r.ok) { setPosted((items) => items.filter((item) => item.id !== id)); setCounts((value) => ({ ...value, posted: Math.max(0, value.posted - 1) })); } else setError("Could not delete the listing."); };
  const logout = async () => { await fetch("/api/auth/logout", { method: "POST", credentials: "include" }); router.push("/"); router.refresh(); };
  if (!profile) return <main className="mx-auto w-full max-w-6xl flex-1 px-4 py-12"><div className="h-64 animate-pulse rounded-3xl bg-white" /></main>;
  const accountType = roleLabel[profile.role] || profile.role;
  return <main className="flex-1 bg-paper"><div className="mx-auto w-full max-w-7xl px-4 py-7 sm:px-6 lg:py-10"><div className="mb-6 flex items-center justify-between lg:hidden"><button onClick={() => setMenu(!menu)} className="inline-flex items-center gap-2 rounded-xl border border-ink/15 bg-white px-3 py-2 text-sm font-medium">{menu ? <X size={17}/> : <Menu size={17}/>} Account menu</button><span className="text-xs text-ink-soft">{accountType}</span></div><div className="flex flex-col gap-5 lg:flex-row"><DashboardSidebar menu={menu} profile={profile} accountType={accountType} section={section} selectSection={selectSection} logout={logout}/><section className="min-w-0 flex-1">{notice && <p className="mb-4 rounded-xl bg-green-50 px-4 py-3 text-sm text-moss-deep">{notice}</p>}{error && <p className="mb-4 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}
    {section === "overview" && <><div className="rounded-3xl bg-ink p-6 text-paper sm:p-8"><p className="text-xs font-semibold uppercase tracking-[.16em] text-gold">Your Bhoomi account</p><h1 className="mt-2 font-display text-3xl sm:text-4xl">Welcome back, {profile.name.split(" ")[0]}</h1><p className="mt-3 text-sm text-paper/70">Manage your saved homes, documents and property activity in one place.</p></div><div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[[Heart, "Saved Properties", counts.saved], [Building2, "My Properties", counts.posted], [FileText, "Documents", counts.documents], [UserRound, "Account Type", accountType]].map(([Icon, label, value]) => <button key={label} onClick={() => label === "Saved Properties" ? selectSection("saved") : label === "My Properties" ? selectSection("posted") : label === "Documents" ? selectSection("documents") : selectSection("profile")} className="rounded-2xl border border-ink/10 bg-white p-5 text-left shadow-sm transition hover:-translate-y-0.5"><Icon className="text-moss" size={21}/><p className="mt-5 text-xs font-semibold uppercase tracking-wide text-ink-soft">{label}</p><p className="mt-1 font-display text-2xl">{value}</p></button>)}</div><div className="mt-5 rounded-2xl border border-ink/10 bg-white p-5 text-sm"><p className="font-semibold">Account information</p><div className="mt-3 grid gap-2 text-ink-soft sm:grid-cols-2"><span>{profile.email}</span><span>{profile.phone}</span><span>Member since {date(profile.createdAt)}</span><span>Status: {profile.verificationStatus}</span></div></div></>}
    {section === "profile" && <><Header title="My Profile" action={!editing && <button onClick={() => setEditing(true)} className="inline-flex items-center gap-2 rounded-full bg-moss px-4 py-2 text-sm font-semibold text-white"><Pencil size={15}/>Edit Profile</button>}/>{editing ? <ProfileForm form={form} setForm={setForm} onSubmit={saveProfile} onCancel={() => setEditing(false)}/> : <div className="rounded-2xl border border-ink/10 bg-white p-6"><div className="flex items-center gap-4"><div className="grid h-16 w-16 place-items-center rounded-full bg-moss/10 font-display text-2xl text-moss">{profile.name[0]}</div><div><p className="font-display text-2xl">{profile.name}</p><p className="text-sm text-ink-soft">{profile.email}</p></div></div><Details values={[["Mobile number",profile.phone],["Account type",accountType],["Registration date",date(profile.createdAt)],["Account status",profile.verificationStatus]]}/></div>}</>}
    {section === "preferences" && <><Header title="Buyer / Renter Details" action={<button onClick={() => { setEditing(true); setSection("profile"); }} className="rounded-full border border-ink/15 px-4 py-2 text-sm font-semibold">Edit preferences</button>}/><div className="rounded-2xl border border-ink/10 bg-white p-6"><p className="text-sm text-ink-soft">Your property requirements help you keep track of your search.</p><Details values={[["Looking to", profile.searchPurpose === "RENT" ? "Rent" : profile.searchPurpose === "SALE" ? "Buy" : "Not specified"],["Preferred city",profile.preferredCity || "Not specified"],["Preferred location",profile.preferredLocation || "Not specified"],["Property type",profile.preferredPropertyType || "Not specified"],["Budget range",profile.budgetRange || "Not specified"],["BHK",profile.preferredBhk || "Not specified"]]}/></div></>}
    {section === "saved" && <><Header title={`Saved Properties (${saved.length})`}/>{saved.length ? <div className="grid gap-4 md:grid-cols-2">{saved.map((l) => <ListingCard key={l.id} listing={l} actions={<><Link href={`/listings/${l.id}`} className="rounded-full bg-moss px-3 py-2 text-xs font-semibold text-white">View Property</Link><button onClick={() => removeSaved(l.id)} className="rounded-full border border-red-200 px-3 py-2 text-xs font-semibold text-red-700">Remove</button></>}/>)}</div> : <EmptyState href="/properties" action="Explore Properties">No saved properties yet.</EmptyState>}</>}
    {section === "documents" && <><Header title={`My Documents (${docs.length})`}/><UserDocuments /></>}
    {section === "posted" && <><Header title={`My Posted Properties (${posted.length})`} action={<Link href="/post-property" className="rounded-full bg-moss px-4 py-2 text-sm font-semibold text-white">Post Property</Link>}/>{posted.length ? <div className="grid gap-4 md:grid-cols-2">{posted.map((l) => <ListingCard key={l.id} listing={l} actions={<><Link href={`/listings/${l.id}`} className="rounded-full bg-moss px-3 py-2 text-xs font-semibold text-white">View</Link><Link href={`/listings/${l.id}/edit`} className="rounded-full border border-ink/15 px-3 py-2 text-xs font-semibold">Edit</Link><button onClick={() => deleteListing(l.id)} className="rounded-full border border-red-200 px-3 py-2 text-xs font-semibold text-red-700">Delete</button></>}/>)}</div> : <EmptyState href="/post-property" action="Post Property">You haven&apos;t posted any property yet.</EmptyState>}</>}
  </section></div></div></main>;
}
function Header({ title, action }) { return <div className="mb-5 flex flex-wrap items-center justify-between gap-3"><h1 className="font-display text-3xl">{title}</h1>{action}</div>; }
function DashboardSidebar({ menu, profile, accountType, section, selectSection, logout }) { return <aside className={`${menu ? "block" : "hidden"} rounded-2xl border border-ink/10 bg-white p-3 shadow-sm lg:block lg:w-64 lg:shrink-0`}><div className="border-b border-ink/10 px-3 pb-4"><p className="font-display text-lg">{profile.name}</p><p className="mt-1 text-xs text-ink-soft">{accountType}</p></div><nav className="mt-3 space-y-1">{nav.map(([key, label, Icon]) => <button key={key} onClick={() => selectSection(key)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm font-medium ${section === key ? "bg-moss text-white" : "text-ink-soft hover:bg-paper"}`}><Icon size={17}/>{label}</button>)}<button onClick={logout} className="mt-3 flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm font-medium text-red-700 hover:bg-red-50"><LogOut size={17}/>Logout</button></nav></aside>; }
function EmptyState({ children, href, action }) { return <div className="rounded-2xl border border-dashed border-ink/20 bg-white px-6 py-12 text-center text-sm text-ink-soft"><p>{children}</p><Link href={href} className="mt-4 inline-block rounded-full bg-moss px-4 py-2 text-xs font-semibold text-white">{action}</Link></div>; }
function Details({ values }) { return <dl className="mt-6 grid gap-4 sm:grid-cols-2">{values.map(([label, value]) => <div key={label} className="rounded-xl bg-paper p-4"><dt className="text-xs font-semibold uppercase tracking-wide text-ink-soft">{label}</dt><dd className="mt-1 text-sm font-medium">{value}</dd></div>)}</dl>; }
function ProfileForm({ form, setForm, onSubmit, onCancel }) { const update = (e) => setForm((f) => ({ ...f, [e.target.name]: e.target.value })); const fields = [["name","Full name"],["phone","Mobile number"],["preferredCity","Preferred city"],["preferredLocation","Preferred location"],["preferredPropertyType","Property type"],["budgetRange","Budget range"],["preferredBhk","BHK"]]; return <form onSubmit={onSubmit} className="rounded-2xl border border-ink/10 bg-white p-6"><p className="mb-5 text-sm text-ink-soft">Email and account type are managed securely and cannot be changed here.</p><div className="grid gap-4 sm:grid-cols-2">{fields.map(([name,label]) => <label key={name} className="text-sm font-medium">{label}<input name={name} value={form[name] || ""} onChange={update} className="mt-1.5 w-full rounded-xl border border-ink/15 px-3 py-2.5" /></label>)}<label className="text-sm font-medium">Looking to<select name="searchPurpose" value={form.searchPurpose || ""} onChange={update} className="mt-1.5 w-full rounded-xl border border-ink/15 bg-white px-3 py-2.5"><option value="">Not specified</option><option value="SALE">Buy</option><option value="RENT">Rent</option></select></label></div><div className="mt-6 flex gap-3"><button className="rounded-full bg-moss px-5 py-2.5 text-sm font-semibold text-white">Save profile</button><button type="button" onClick={onCancel} className="rounded-full border border-ink/15 px-5 py-2.5 text-sm font-semibold">Cancel</button></div></form>; }
function ListingCard({ listing, actions }) { const photo = listing.photos?.[0]?.url; return <article className="overflow-hidden rounded-2xl border border-ink/10 bg-white shadow-sm">{photo ? <img src={photo} alt="" className="h-40 w-full object-cover"/> : <div className="grid h-40 place-items-center bg-paper text-ink-soft"><Building2/></div>}<div className="p-5"><div className="flex items-start justify-between gap-2"><h2 className="font-display text-xl">{listing.title}</h2><span className="rounded-full bg-paper px-2 py-1 text-[10px] font-semibold">{listing.status}</span></div><p className="mt-2 text-sm text-ink-soft">{listing.propertyType} · {listing.area}, {listing.city}</p><p className="mt-2 font-semibold">{formatPrice(listing.price, listing.purpose)}</p><p className="mt-1 text-xs text-ink-soft">{listing.bedrooms ? `${listing.bedrooms} BHK · ` : ""}{listing.sizeValue ? `${listing.sizeValue} ${listing.sizeUnit || "sq.ft."}` : ""}</p><div className="mt-4 flex flex-wrap gap-2">{actions}</div></div></article>; }
